### ISSUE TITLE
请问部分新增依赖如何安装，npm上没有找到。 

### ISSUE THREAD

**Issue by Chenghui-web** [open-hand/choerodon-front-master#3]
"@hzero-front-ui/c7n-ui": "3.1.0-alpha.9",
    "@hzero-front-ui/core": "3.0.1-alpha.2",
    "@hzero-front-ui/themes": "3.1.0-alpha.9",

**Comment by chenshouzuo** [comment]
> "@hzero-front-ui/c7n-ui": "3.1.0-alpha.9", "@hzero-front-ui/core": "3.0.1-alpha.2", "@hzero-front-ui/themes": "3.1.0-alpha.9",

你好 请问你解决了吗？

**Comment by chenshouzuo** [comment]
> "@hzero-front-ui/c7n-ui": "3.1.0-alpha.9", "@hzero-front-ui/core": "3.0.1-alpha.2", "@hzero-front-ui/themes": "3.1.0-alpha.9",

@Chenghui-web  你好 请问这个问题你解决了吗？
